# 張量 Tensor

類似 Numpy 的 ndarrays

In [2]:
import numpy as np
import torch

In [26]:
x = np.array([[1, 2], [3, 4]])
print(x)

[[1 2]
 [3 4]]


## Convert a Numpy array to a Pytorch tensor using <code>torch.from_numpy</code>

In [28]:
y = torch.from_numpy(x)
print(y)

# torch.tensor(x)

tensor([[1, 2],
        [3, 4]])


## Convert a Pytorch tensor to a Numpy array using <code>torch.from_numpy</code> method of a tensor

In [29]:
z = y.numpy()
z

array([[1, 2],
       [3, 4]])

## create a tensor

In [31]:
x = torch.empty(5, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [38]:
x = torch.rand(5, 3)
print(x)

tensor([[0.4812, 0.0427, 0.6822],
        [0.8118, 0.4269, 0.0614],
        [0.1495, 0.9224, 0.0615],
        [0.1974, 0.2948, 0.1922],
        [0.1706, 0.8659, 0.2356]])


In [33]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [34]:
print(x.size())

torch.Size([5, 3])


# Operation

In [39]:
y = torch.rand(5, 3)
print(x + y)

tensor([[0.7952, 0.5936, 0.7809],
        [0.8396, 0.5255, 0.2347],
        [1.0429, 1.6677, 0.9174],
        [1.1149, 1.2375, 0.6514],
        [0.3392, 1.8333, 1.1656]])


In [40]:
print(torch.add(x, y))

tensor([[0.7952, 0.5936, 0.7809],
        [0.8396, 0.5255, 0.2347],
        [1.0429, 1.6677, 0.9174],
        [1.1149, 1.2375, 0.6514],
        [0.3392, 1.8333, 1.1656]])


## 索引操作

In [41]:
print(x[:, 1])

tensor([0.0427, 0.4269, 0.9224, 0.2948, 0.8659])


## 改變 tensor 大小或形狀 using torch.view

In [3]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8) # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())
print(x)
print(y)
print(z)

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
tensor([[ 1.7071, -1.7035,  0.1418,  0.5257],
        [-1.0768, -0.0432,  0.4301,  0.9369],
        [-2.0420,  0.0717, -0.2194, -2.5300],
        [-0.1578, -0.9972, -0.3839,  0.3259]])
tensor([ 1.7071, -1.7035,  0.1418,  0.5257, -1.0768, -0.0432,  0.4301,  0.9369,
        -2.0420,  0.0717, -0.2194, -2.5300, -0.1578, -0.9972, -0.3839,  0.3259])
tensor([[ 1.7071, -1.7035,  0.1418,  0.5257, -1.0768, -0.0432,  0.4301,  0.9369],
        [-2.0420,  0.0717, -0.2194, -2.5300, -0.1578, -0.9972, -0.3839,  0.3259]])


## using <code>torch.item()</code> to get value

In [4]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.8990])
0.8989546895027161
